# Generated by Django 6.0.4 on 2026-05-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_callrequest_consultationrequest_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='svg_icon',
            field=models.TextField(blank=True, default='', verbose_name='SVG иконка'),
        ),
    ]
