# Generated by Django 6.0.4 on 2026-05-11 03:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_service_svg_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('consultation', 'Консультация / обратный звонок (форма внизу)'), ('callback', 'Обратный звонок (карточка на главной)'), ('calculation', 'Расчёт стоимости СОУТ'), ('contact_form', 'Форма контактов'), ('service', 'Заявка с страницы услуги')], default='contact_form', max_length=32, verbose_name='Тип заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Обработана')], default='new', max_length=20, verbose_name='Статус')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='ФИО / имя')),
                ('phone', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +7 (XXX) XXX-XX-XX', regex='^\\+7 \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, default='', verbose_name='Сообщение / комментарий')),
                ('call_time', models.CharField(blank=True, default='', max_length=120, verbose_name='Удобное время звонка')),
                ('employees_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество сотрудников (СОУТ)')),
                ('workplaces_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество рабочих мест (СОУТ)')),
                ('enterprise_type', models.CharField(blank=True, default='', max_length=120, verbose_name='Тип предприятия (СОУТ)')),
                ('admin_comment', models.TextField(blank=True, default='', verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='main.service', verbose_name='Услуга')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лид (заявка)',
                'verbose_name_plural': 'Лиды (заявки)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CallRequest',
        ),
        migrations.DeleteModel(
            name='ConsultationRequest',
        ),
        migrations.DeleteModel(
            name='ContactRequest',
        ),
    ]
