# Generated by Django 6.0.4 on 2026-05-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('consultation', 'Консультация / обратный звонок'), ('callback', 'Обратный звонок'), ('calculation', 'Расчёт стоимости СОУТ'), ('contact_form', 'Форма контактов'), ('service', 'Заявка с страницы услуги')], default='contact_form', max_length=32, verbose_name='Тип заявки'),
        ),
    ]
