# Generated by Django 6.0.4 on 2026-05-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_lead_lead_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='banner_bg',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Фон баннера (url или цвет)'),
        ),
        migrations.AddField(
            model_name='service',
            name='banner_subtitle',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подзаголовок на баннере'),
        ),
        migrations.AddField(
            model_name='service',
            name='banner_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок на баннере'),
        ),
    ]
