# Generated by Django 6.0.4 on 2026-05-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_service_banner_bg_service_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content_blocks',
            field=models.JSONField(blank=True, default=dict, verbose_name='Блоки контента'),
        ),
    ]
